[project]
name = "parser-hh-ru-to-file"
version = "0.1.0"
description = ""
authors = [
    {name = "Rodion Ventslovsky",email = "vents_23@mail.ru"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests (>=2.32.5,<3.0.0)"
]

[tool.poetry]
packages = [{include = "parser_hh"}]


[tool.poetry.group.dev.dependencies]
pytest = "^9.0.1"
pytest-cov = "^7.0.0"
flake8 = "^7.3.0"
mypy = "^1.19.0"
isort = "^7.0.0"
black = "^25.11.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 109
target-version = ['py313']

[tool.isort]
profile = "black"
line_length = 109

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true


[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --cov=parser_hh_ru_to_file --cov-report=term-missing --cov-report=html"


[tool.poetry.scripts]
format = "isort . && black ."
lint = "flake8 parser_hh_ru_to_file tests"
type-check = "mypy parser_hh_ru_to_file"
test = "pytest"
test-cov = "pytest --cov=parser_hh_ru_to_file"
all-checks = "isort --check-only . && black --check . && flake8 parser_hh_ru_to_file tests && mypy parser_hh_ru_to_file"
#poetry run format    # форматирование кода
#poetry run lint      # проверка стиля
#poetry run type-check # проверка типов
#poetry run test      # запуск тестов
#poetry run all-checks # все проверки